version: "3.9"

services:
  mongo_subscriptions:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: subscriptiondb
    ports:
      - "27017:27017"
    volumes:
      - mongo_subs:/data/db
  subscriptions:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mongo_subscriptions
    environment:
      MONGO_URI: "mongodb://root:root@mongo_subscriptions:27017"
volumes:
  mongo_subs: